import { env } from "./config";

export const servicePathPrefix = "/presenter-account";

export const Urls = {
    ACCESSIBILITY_STATEMENT: "/accessibility-statement",
    HOME: "/",
    HEALTHCHECK: "/healthcheck",
    APPLY_TO_FILE_OPTIONS: "/what-do-you-need-to-file",
    ENTER_YOUR_DETAILS: "/enter-your-details",
    CHECK_DETAILS: "/check_details",
    SIGN_IN: "/sign-in",
    YOU_CANNOT_USE_THIS_SERVICE: "/you-cannot-use-this-service",
    CONFIRMATION: "/confirmation",
    SUBMITTED: "/submitted"
} as const;

export const PrefixedUrls = {
    ACCESSIBILITY_STATEMENT: servicePathPrefix + Urls.ACCESSIBILITY_STATEMENT,
    HOME: servicePathPrefix + Urls.HOME,
    APPLY_TO_FILE_OPTIONS: servicePathPrefix + Urls.APPLY_TO_FILE_OPTIONS,
    HEALTHCHECK: servicePathPrefix + Urls.HEALTHCHECK,
    ENTER_YOUR_DETAILS: servicePathPrefix + Urls.ENTER_YOUR_DETAILS,
    CHECK_DETAILS: servicePathPrefix + Urls.CHECK_DETAILS,
    YOU_CANNOT_USE_THIS_SERVICE: servicePathPrefix + Urls.YOU_CANNOT_USE_THIS_SERVICE,
    SIGN_IN: servicePathPrefix + Urls.SIGN_IN,
    CONFIRMATION: servicePathPrefix + Urls.CONFIRMATION,
    SUBMITTED: servicePathPrefix + Urls.SUBMITTED,
    COOKIES: "/help/cookies"
} as const;

export const ExternalUrls = {
    ABILITY_NET: env.ABILITY_NET_LINK,
    CONTACT_US: env.CONTACT_US_LINK,
    DEVELOPERS: env.DEVELOPERS_LINK,
    FEEDBACK: env.FEEDBACK_URL,
    OPEN_GOVERNMENT_LICENSE: env.OPEN_GOVERNMENT_LICENSE_LINK,
    POLICIES: env.POLICIES_LINK,
} as const;

const selectCountryData = [
    { value: 'Aruba', text: 'Aruba' },
    { value: 'Afghanistan', text: 'Afghanistan' },
    { value: 'Angola', text: 'Angola' },
    { value: 'Anguilla', text: 'Anguilla' },
    { value: 'Aland Islands', text: 'Aland Islands' },
    { value: 'Albania', text: 'Albania' },
    { value: 'Andorra', text: 'Andorra' },
    { value: 'United Arab Emirates', text: 'United Arab Emirates' },
    { value: 'Argentina', text: 'Argentina' },
    { value: 'Armenia', text: 'Armenia' },
    { value: 'American Samoa', text: 'American Samoa' },
    { value: 'Antarctica', text: 'Antarctica' },
    { value: 'French Southern Territories', text: 'French Southern Territories' },
    { value: 'Antigua and Barbuda', text: 'Antigua and Barbuda' },
    { value: 'Australia', text: 'Australia' },
    { value: 'Austria', text: 'Austria' },
    { value: 'Azerbaijan', text: 'Azerbaijan' },
    { value: 'Burundi', text: 'Burundi' },
    { value: 'Belgium', text: 'Belgium' },
    { value: 'Benin', text: 'Benin' },
    { value: 'Bonaire, Sint Eustatius and Saba', text: 'Bonaire, Sint Eustatius and Saba' },
    { value: 'Burkina Faso', text: 'Burkina Faso' },
    { value: 'Bangladesh', text: 'Bangladesh' },
    { value: 'Bulgaria', text: 'Bulgaria' },
    { value: 'Bahrain', text: 'Bahrain' },
    { value: 'Bahamas', text: 'Bahamas' },
    { value: 'Bosnia and Herzegovina', text: 'Bosnia and Herzegovina' },
    { value: 'Saint Barthélemy', text: 'Saint Barthélemy' },
    { value: 'Belarus', text: 'Belarus' },
    { value: 'Belize', text: 'Belize' },
    { value: 'Bermuda', text: 'Bermuda' },
    { value: 'Bolivia, Plurinational State of', text: 'Bolivia, Plurinational State of' },
    { value: 'Brazil', text: 'Brazil' },
    { value: 'Barbados', text: 'Barbados' },
    { value: 'Brunei Darussalam', text: 'Brunei Darussalam' },
    { value: 'Bhutan', text: 'Bhutan' },
    { value: 'Bouvet Island', text: 'Bouvet Island' },
    { value: 'Botswana', text: 'Botswana' },
    { value: 'Central African Republic', text: 'Central African Republic' },
    { value: 'Canada', text: 'Canada' },
    { value: 'Cocos (Keeling) Islands', text: 'Cocos (Keeling) Islands' },
    { value: 'Switzerland', text: 'Switzerland' },
    { value: 'Chile', text: 'Chile' },
    { value: 'China', text: 'China' },
    { value: 'Côte d\'Ivoire', text: 'Côte d\'Ivoire' },
    { value: 'Cameroon', text: 'Cameroon' },
    { value: 'Congo, The Democratic Republic of the', text: 'Congo, The Democratic Republic of the' },
    { value: 'Congo', text: 'Congo' },
    { value: 'Cook Islands', text: 'Cook Islands' },
    { value: 'Colombia', text: 'Colombia' },
    { value: 'Comoros', text: 'Comoros' },
    { value: 'Cabo Verde', text: 'Cabo Verde' },
    { value: 'Costa Rica', text: 'Costa Rica' },
    { value: 'Cuba', text: 'Cuba' },
    { value: 'Curaçao', text: 'Curaçao' },
    { value: 'Christmas Island', text: 'Christmas Island' },
    { value: 'Cayman Islands', text: 'Cayman Islands' },
    { value: 'Cyprus', text: 'Cyprus' },
    { value: 'Czechia', text: 'Czechia' },
    { value: 'Germany', text: 'Germany' },
    { value: 'Djibouti', text: 'Djibouti' },
    { value: 'Dominica', text: 'Dominica' },
    { value: 'Denmark', text: 'Denmark' },
    { value: 'Dominican Republic', text: 'Dominican Republic' },
    { value: 'Algeria', text: 'Algeria' },
    { value: 'Ecuador', text: 'Ecuador' },
    { value: 'Egypt', text: 'Egypt' },
    { value: 'Eritrea', text: 'Eritrea' },
    { value: 'Western Sahara', text: 'Western Sahara' },
    { value: 'Spain', text: 'Spain' },
    { value: 'Estonia', text: 'Estonia' },
    { value: 'Ethiopia', text: 'Ethiopia' },
    { value: 'Finland', text: 'Finland' },
    { value: 'Fiji', text: 'Fiji' },
    { value: 'Falkland Islands (Malvinas)', text: 'Falkland Islands (Malvinas)' },
    { value: 'France', text: 'France' },
    { value: 'Faroe Islands', text: 'Faroe Islands' },
    { value: 'Micronesia, Federated States of', text: 'Micronesia, Federated States of' },
    { value: 'Gabon', text: 'Gabon' },
    { value: 'United Kingdom', text: 'United Kingdom' },
    { value: 'Georgia', text: 'Georgia' },
    { value: 'Guernsey', text: 'Guernsey' },
    { value: 'Ghana', text: 'Ghana' },
    { value: 'Gibraltar', text: 'Gibraltar' },
    { value: 'Guinea', text: 'Guinea' },
    { value: 'Guadeloupe', text: 'Guadeloupe' },
    { value: 'Gambia', text: 'Gambia' },
    { value: 'Guinea-Bissau', text: 'Guinea-Bissau' },
    { value: 'Equatorial Guinea', text: 'Equatorial Guinea' },
    { value: 'Greece', text: 'Greece' },
    { value: 'Grenada', text: 'Grenada' },
    { value: 'Greenland', text: 'Greenland' },
    { value: 'Guatemala', text: 'Guatemala' },
    { value: 'French Guiana', text: 'French Guiana' },
    { value: 'Guam', text: 'Guam' },
    { value: 'Guyana', text: 'Guyana' },
    { value: 'Hong Kong', text: 'Hong Kong' },
    { value: 'Heard Island and McDonald Islands', text: 'Heard Island and McDonald Islands' },
    { value: 'Honduras', text: 'Honduras' },
    { value: 'Croatia', text: 'Croatia' },
    { value: 'Haiti', text: 'Haiti' },
    { value: 'Hungary', text: 'Hungary' },
    { value: 'Indonesia', text: 'Indonesia' },
    { value: 'Isle of Man', text: 'Isle of Man' },
    { value: 'India', text: 'India' },
    { value: 'British Indian Ocean Territory', text: 'British Indian Ocean Territory' },
    { value: 'Ireland', text: 'Ireland' },
    { value: 'Iran, Islamic Republic of', text: 'Iran, Islamic Republic of' },
    { value: 'Iraq', text: 'Iraq' },
    { value: 'Iceland', text: 'Iceland' },
    { value: 'Israel', text: 'Israel' },
    { value: 'Italy', text: 'Italy' },
    { value: 'Jamaica', text: 'Jamaica' },
    { value: 'Jersey', text: 'Jersey' },
    { value: 'Jordan', text: 'Jordan' },
    { value: 'Japan', text: 'Japan' },
    { value: 'Kazakhstan', text: 'Kazakhstan' },
    { value: 'Kenya', text: 'Kenya' },
    { value: 'Kyrgyzstan', text: 'Kyrgyzstan' },
    { value: 'Cambodia', text: 'Cambodia' },
    { value: 'Kiribati', text: 'Kiribati' },
    { value: 'Saint Kitts and Nevis', text: 'Saint Kitts and Nevis' },
    { value: 'Korea, Republic of', text: 'Korea, Republic of' },
    { value: 'Kuwait', text: 'Kuwait' },
    { value: 'Lao People\'s Democratic Republic', text: 'Lao People\'s Democratic Republic' },
    { value: 'Lebanon', text: 'Lebanon' },
    { value: 'Liberia', text: 'Liberia' },
    { value: 'Libya', text: 'Libya' },
    { value: 'Saint Lucia', text: 'Saint Lucia' },
    { value: 'Liechtenstein', text: 'Liechtenstein' },
    { value: 'Sri Lanka', text: 'Sri Lanka' },
    { value: 'Lesotho', text: 'Lesotho' },
    { value: 'Lithuania', text: 'Lithuania' },
    { value: 'Luxembourg', text: 'Luxembourg' },
    { value: 'Latvia', text: 'Latvia' },
    { value: 'Macao', text: 'Macao' },
    { value: 'Saint Martin (French part)', text: 'Saint Martin (French part)' },
    { value: 'Morocco', text: 'Morocco' },
    { value: 'Monaco', text: 'Monaco' },
    { value: 'Moldova, Republic of', text: 'Moldova, Republic of' },
    { value: 'Madagascar', text: 'Madagascar' },
    { value: 'Maldives', text: 'Maldives' },
    { value: 'Mexico', text: 'Mexico' },
    { value: 'Marshall Islands', text: 'Marshall Islands' },
    { value: 'North Macedonia', text: 'North Macedonia' },
    { value: 'Mali', text: 'Mali' },
    { value: 'Malta', text: 'Malta' },
    { value: 'Myanmar', text: 'Myanmar' },
    { value: 'Montenegro', text: 'Montenegro' },
    { value: 'Mongolia', text: 'Mongolia' },
    { value: 'Northern Mariana Islands', text: 'Northern Mariana Islands' },
    { value: 'Mozambique', text: 'Mozambique' },
    { value: 'Mauritania', text: 'Mauritania' },
    { value: 'Montserrat', text: 'Montserrat' },
    { value: 'Martinique', text: 'Martinique' },
    { value: 'Mauritius', text: 'Mauritius' },
    { value: 'Malawi', text: 'Malawi' },
    { value: 'Malaysia', text: 'Malaysia' },
    { value: 'Mayotte', text: 'Mayotte' },
    { value: 'Namibia', text: 'Namibia' },
    { value: 'New Caledonia', text: 'New Caledonia' },
    { value: 'Niger', text: 'Niger' },
    { value: 'Norfolk Island', text: 'Norfolk Island' },
    { value: 'Nigeria', text: 'Nigeria' },
    { value: 'Nicaragua', text: 'Nicaragua' },
    { value: 'Niue', text: 'Niue' },
    { value: 'Netherlands', text: 'Netherlands' },
    { value: 'Norway', text: 'Norway' },
    { value: 'Nepal', text: 'Nepal' },
    { value: 'Nauru', text: 'Nauru' },
    { value: 'New Zealand', text: 'New Zealand' },
    { value: 'Oman', text: 'Oman' },
    { value: 'Pakistan', text: 'Pakistan' },
    { value: 'Panama', text: 'Panama' },
    { value: 'Pitcairn', text: 'Pitcairn' },
    { value: 'Peru', text: 'Peru' },
    { value: 'Philippines', text: 'Philippines' },
    { value: 'Palau', text: 'Palau' },
    { value: 'Papua New Guinea', text: 'Papua New Guinea' },
    { value: 'Poland', text: 'Poland' },
    { value: 'Puerto Rico', text: 'Puerto Rico' },
    { value: 'Korea, Democratic People\'s Republic of', text: 'Korea, Democratic People\'s Republic of' },
    { value: 'Portugal', text: 'Portugal' },
    { value: 'Paraguay', text: 'Paraguay' },
    { value: 'Palestine, State of', text: 'Palestine, State of' },
    { value: 'French Polynesia', text: 'French Polynesia' },
    { value: 'Qatar', text: 'Qatar' },
    { value: 'Réunion', text: 'Réunion' },
    { value: 'Romania', text: 'Romania' },
    { value: 'Russian Federation', text: 'Russian Federation' },
    { value: 'Rwanda', text: 'Rwanda' },
    { value: 'Saudi Arabia', text: 'Saudi Arabia' },
    { value: 'Sudan', text: 'Sudan' },
    { value: 'Senegal', text: 'Senegal' },
    { value: 'Singapore', text: 'Singapore' },
    { value: 'South Georgia and the South Sandwich Islands', text: 'South Georgia and the South Sandwich Islands' },
    { value: 'Saint Helena, Ascension and Tristan da Cunha', text: 'Saint Helena, Ascension and Tristan da Cunha' },
    { value: 'Svalbard and Jan Mayen', text: 'Svalbard and Jan Mayen' },
    { value: 'Solomon Islands', text: 'Solomon Islands' },
    { value: 'Sierra Leone', text: 'Sierra Leone' },
    { value: 'El Salvador', text: 'El Salvador' },
    { value: 'San Marino', text: 'San Marino' },
    { value: 'Somalia', text: 'Somalia' },
    { value: 'Saint Pierre and Miquelon', text: 'Saint Pierre and Miquelon' },
    { value: 'Serbia', text: 'Serbia' },
    { value: 'South Sudan', text: 'South Sudan' },
    { value: 'Sao Tome and Principe', text: 'Sao Tome and Principe' },
    { value: 'Suriname', text: 'Suriname' },
    { value: 'Slovakia', text: 'Slovakia' },
    { value: 'Slovenia', text: 'Slovenia' },
    { value: 'Sweden', text: 'Sweden' },
    { value: 'Eswatini', text: 'Eswatini' },
    { value: 'Sint Maarten (Dutch part)', text: 'Sint Maarten (Dutch part)' },
    { value: 'Seychelles', text: 'Seychelles' },
    { value: 'Syrian Arab Republic', text: 'Syrian Arab Republic' },
    { value: 'Turks and Caicos Islands', text: 'Turks and Caicos Islands' },
    { value: 'Chad', text: 'Chad' },
    { value: 'Togo', text: 'Togo' },
    { value: 'Thailand', text: 'Thailand' },
    { value: 'Tajikistan', text: 'Tajikistan' },
    { value: 'Tokelau', text: 'Tokelau' },
    { value: 'Turkmenistan', text: 'Turkmenistan' },
    { value: 'Timor-Leste', text: 'Timor-Leste' },
    { value: 'Tonga', text: 'Tonga' },
    { value: 'Trinidad and Tobago', text: 'Trinidad and Tobago' },
    { value: 'Tunisia', text: 'Tunisia' },
    { value: 'Turkey', text: 'Turkey' },
    { value: 'Tuvalu', text: 'Tuvalu' },
    { value: 'Taiwan, Province of China', text: 'Taiwan, Province of China' },
    { value: 'Tanzania, United Republic of', text: 'Tanzania, United Republic of' },
    { value: 'Uganda', text: 'Uganda' },
    { value: 'Ukraine', text: 'Ukraine' },
    { value: 'United States Minor Outlying Islands', text: 'United States Minor Outlying Islands' },
    { value: 'Uruguay', text: 'Uruguay' },
    { value: 'United States', text: 'United States' },
    { value: 'Uzbekistan', text: 'Uzbekistan' },
    { value: 'Holy See (Vatican City State)', text: 'Holy See (Vatican City State)' },
    { value: 'Saint Vincent and the Grenadines', text: 'Saint Vincent and the Grenadines' },
    { value: 'Venezuela, Bolivarian Republic of', text: 'Venezuela, Bolivarian Republic of' },
    { value: 'Virgin Islands, British', text: 'Virgin Islands, British' },
    { value: 'Virgin Islands, U.S.', text: 'Virgin Islands, U.S.' },
    { value: 'Viet Nam', text: 'Viet Nam' },
    { value: 'Vanuatu', text: 'Vanuatu' },
    { value: 'Wallis and Futuna', text: 'Wallis and Futuna' },
    { value: 'Samoa', text: 'Samoa' },
    { value: 'Yemen', text: 'Yemen' },
    { value: 'South Africa', text: 'South Africa' },
    { value: 'Zambia', text: 'Zambia' },
    { value: 'Zimbabwe', text: 'Zimbabwe' },
];

export const Countries = selectCountryData.sort((country1, country2) => country1.text.localeCompare(country2.text));
